# directive: gotemplate

{{ if .http.enabled -}}
{{ with .http.snippet -}}
{{ include (printf "%s%s" "{{ \"\" -}}\n" . ) $ }}
{{- end }}

{{ range $server := .http.servers -}}
{{ if $server.snippet -}}
server {
  {{- with $server.snippet -}}
  {{ include (printf "%s%s" "{{ \"\" -}}\n" . ) $ | nindent 2 }}
  {{- end }}
}
{{- else -}}
# some server snippet was skipped
{{- end }}

{{ end -}}
{{- end -}}
