# directive: gotemplate

include modules.conf;

{{- with .global.snippet }}
{{ include (printf "%s%s" "{{ \"\" -}}\n" . ) $ }}
{{- end }}

http {
  include mime.types;

  map_hash_bucket_size {{ .global.map_hash_bucket_size | default 4096 }};

  ###
  ### Http configurations
  ###
  include http.d/*.conf;

  ###
  ### Http router
  ###
  include http.conf;
}

stream {
  map_hash_bucket_size {{ .global.map_hash_bucket_size | default 4096 }};

  ###
  ### Stream configurations
  ###
  include stream.d/*.conf;

  ###
  ### Premux is a TLS pre-read multiplexer. It can route incoming TLS
  ### and non-TLS connections (recognizes!) to different upstreams based
  ### on SNI and ALPN in TLS ClientHello. It does not terminate TLS allowing
  ### to use client certificates and remain end-to-end encryption.
  ###
  include premux.conf;
}
