map "$time_iso8601" $time_iso8601_norm {
    "~^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(Z|\+00:00|)$" $1Z;
    "~^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(Z|\+\d{2}:\d{2}|)$" $1$2;
}

map "$time_iso8601_norm:$msec" $time_iso8601_ms {
    "~^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(Z|\+\d{2}:\d{2}|):(\d+)\.(\d+)$" $1.$4$2;
}

log_format   main 'STREAM->:$server_port: [$remote_addr|$proxy_protocol_addr] [$time_iso8601_ms] '
                  '$status [${session_time}s] IN:$bytes_received OUT:$bytes_sent';

log_format  debug 'STREAM->:$server_port: [$remote_addr|$proxy_protocol_addr] [$time_iso8601_ms] '
                  '$status [${session_time}s] IN:$bytes_received OUT:$bytes_sent '
                  'ID:$connection RA:$remote_addr PPA:$proxy_protocol_addr '
                  'UPS:$premux_upstream UPSP:$premux_upstream_pre '
                  '_PROT:$premux_protocol _PP:$premux_proxy_protocol _WL:$premux_whitelist '
                  'SPRP:$ssl_preread_protocol SPRALPN:$ssl_preread_alpn_protocols SPRSNI:$ssl_preread_server_name';

access_log  /var/log/nginx/access.log  main;
