lua_package_path "/usr/local/lib/lua/?.lua;/usr/local/lib/lua/?/init.lua;;";
lua_package_cpath "/usr/local/lib/lua/5.1/?.so;;";

init_by_lua_block {
    ngx.log(ngx.NOTICE, "Lua libraries have been successfuly initialized");
}
