map "$time_iso8601" $time_iso8601_norm {
    "~^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(Z|\+00:00|)$" $1Z;
    "~^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(Z|\+\d{2}:\d{2}|)$" $1$2;
}

map "$time_iso8601_norm:$msec" $time_iso8601_ms {
    "~^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(Z|\+\d{2}:\d{2}|):(\d+)\.(\d+)$" $1.$4$2;
}

log_format   main  'HTTP->:$server_port: [$remote_addr|$proxy_protocol_addr] [$time_iso8601_ms] "$request" '
                   '$status [${request_time}s] $body_bytes_sent "$http_referer" '
                   '"$http_user_agent" "$http_x_forwarded_for"';

log_format  debug  'HTTP->:$server_port: [$remote_addr|$proxy_protocol_addr] [$time_iso8601_ms] "$request" '
                   '$status [${request_time}s] $body_bytes_sent "$http_referer" '
                   '"$http_user_agent" "$http_x_forwarded_for" '
                   'ID:$request_id '
                   '"SERIAL=$connection:NUM=$connection_requests:DUR=$connection_time" '
                   '"RA:$remote_addr PPA:$proxy_protocol_addr XFF:$http_x_forwarded_for"';

access_log  /var/log/nginx/access.log  main;
