http:
  ###
  ### Enable or disable http templating module.
  ###
  enabled: true

  ###
  ### This snippet will be added to the http block in nginx
  ### configuration, as is. You can use it to set any http level
  ### configuration, including additional maps, variables, extra server
  ### definitions, default settings, etc.
  ###
  snippet: |-
    sendfile  on;

    gzip               off;
    gzip_proxied       off;
    gzip_static        off;
    gzip_buffers       16 16k;
    gzip_comp_level    3;
    gzip_http_version  1.1;
    gzip_min_length    1000;

    http2                         on;
    http2_max_concurrent_streams  128;

    keepalive_timeout 3m;
    keepalive_requests 1000;

    client_max_body_size  4G;

    client_header_buffer_size    16k;
    client_body_buffer_size      16k;
    large_client_header_buffers  4 32k;

    proxy_busy_buffers_size    32k;
    proxy_buffers            8 16k;
    proxy_buffer_size          16k;

    default_type  application/octet-stream;

    {{ if .global.resolver -}}
    resolver {{ .global.resolver }};

    {{ end -}}

    ssl_protocols TLSv1.3;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    {{ if .dhparams.found -}}
    ssl_dhparam {{ .dhparams.file }};
    {{- end }}

    {{ if .global.resolver -}}
    ssl_stapling on;
    {{ if exists "/etc/ssl/certs/ca-certificates.crt" -}}
    ssl_stapling_verify on;
    {{- end }}

    {{ end -}}

    {{ if exists "/etc/ssl/certs/ca-certificates.crt" -}}
    ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    {{ end -}}

    # Hide some headers for security reasons
    server_tokens            off;
    server_name_in_redirect  off;
    more_clear_headers       'X-Hidden-*';
    more_clear_headers       'X-Powered-*';
    more_clear_headers       'Server';
    more_clear_headers       'X-Forwarded-Server';

    # Basic proxy settings
    proxy_http_version     1.1;
    proxy_socket_keepalive on;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    Upgrade $http_upgrade;
    proxy_set_header    Connection $http_connection;
    proxy_cache_bypass  $http_upgrade;

  ###
  ### Servers can have only snippet field which will be templated
  ### by the same context and added into http block. If you want to
  ### add an upstream or map block, you can append it to the non-server
  ### snippet (above).
  ###
  servers:
    - snippet: |-
        listen [::]:80 ipv6only=off default_server;

        root /var/empty;
        index index.html;

        location ^~ /.well-known/ {
            alias /data/.well-known/;

            limit_except GET {
                deny all;
            }

            access_log off;
            log_not_found off;
        }

        location / {
          # 307 - temporary, 308 - permanent
          return 307 https://$host$request_uri;
        }

        # Security comment: that is not open redirect because it is on the
        # same host, but it's still better to avoid it if your list of domains
        # can vary by external configuration (customer-supplied, etc.).
    - snippet: |-
        # default http server
        listen 127.0.0.1:8443 default_server ssl proxy_protocol;

        {{ $selected_ssl_ceritificate := "default" -}}

        {{- range $key, $_ := (. | get "ssl-certificates") -}}
          {{- if regexMatch `^[\d]+\.[\d]+\.[\d]+\.[\d]+$` $key -}}
            {{- $selected_ssl_ceritificate = $key -}}
          {{- end -}}
        {{- end -}}

        ssl_certificate {{ . | get "ssl-certificates" | get $selected_ssl_ceritificate | get "cert_file" }};
        ssl_certificate_key {{ . | get "ssl-certificates" | get $selected_ssl_ceritificate | get "key_file" }};

        real_ip_header proxy_protocol;
        real_ip_recursive on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location / {
          return 200 "Hello, World!";
        }
    - snippet: |-
        # another http server
        listen 127.0.0.1:8443 ssl proxy_protocol;
        server_name killerbot-api.local;

        {{ $selected_ssl_ceritificate := "default" -}}

        {{- range $key, $_ := (. | get "ssl-certificates") -}}
          {{- if eq "killerbot-api.local" $key -}}
            {{- $selected_ssl_ceritificate = $key -}}
          {{- end -}}
        {{- end -}}

        ssl_certificate {{ . | get "ssl-certificates" | get $selected_ssl_ceritificate | get "cert_file" }};
        ssl_certificate_key {{ . | get "ssl-certificates" | get $selected_ssl_ceritificate | get "key_file" }};

        real_ip_header proxy_protocol;
        real_ip_recursive on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location / {
          ###
          ### Don't leave it enabled if you finished to debug your configuration. This guy
          ### who developed this service is a real hero, don't push his AWS bill up.
          ### In addition, this allows to enable some tricky hacks and discovery tricks of
          ### 3rd party services, so it might be also a security risk for you (low but still).
          ###
          # proxy_pass https://httpbin.org;
          return 200 "Hello, World!";
        }
